<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Motivo\Module'                        => __DIR__ . '/Module.php',
    'Motivo\Controller\IndexController' => __DIR__ . '/src/Motivo/Controller/IndexController.php',
    'MotivoTest\Framework\TestCase'        => __DIR__ . '/tests/Motivo/Framework/TestCase.php',
    'MotivoTest\SampleTest'                => __DIR__ . '/tests/Motivo/SampleTest.php',
);
